apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-demo
  labels:
    app: html-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-demo  # This MUST match the template label below
  template:
    metadata:
      labels:
        app: html-demo # This is the label applied to the Pods
    spec:
      containers:
      - name: html-demo-container
        image: 23mis0617/html-demo # Use the image you just pushed
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-demo-service
spec:
  selector:
    app: html-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
